- name: Update and upgrade system packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist

- name: Install MySQL server
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Configure MySQL
  block:
    - name: Update MySQL configuration
      ansible.builtin.lineinfile:
        path: /etc/mysql/my.cnf
        line: "{{ item }}"
        create: yes
      with_items:
        - "[mysqld]"
        - "port={{ db_master_port }}"
        - "bind-address = 0.0.0.0"
        - "server-id = 1"
        - "log_bin = /var/log/mysql/mysql-bin.log"

    - name: Restart MySQL service
      ansible.builtin.service:
        name: mysql
        state: restarted

- name: Set up MySQL database and user
  ansible.builtin.shell: |
    mysql -e "CREATE USER IF NOT EXISTS 'petclinic'@'%' IDENTIFIED BY 'petclinic';"
    mysql -e "CREATE DATABASE IF NOT EXISTS petclinic;"
    mysql -e "GRANT ALL PRIVILEGES ON petclinic.* TO 'petclinic'@'%' WITH GRANT OPTION;"
    mysql -e "CREATE USER 'replica_petclinic'@'%' IDENTIFIED WITH mysql_native_password BY 'replica_petclinic';"
    mysql -e "GRANT REPLICATION SLAVE ON *.* TO 'replica_petclinic'@'%';"
    mysql -e "FLUSH PRIVILEGES;"
  args:
    executable: /bin/bash

- name: Download and prepare schema.sql
  ansible.builtin.shell: |
    wget -q https://raw.githubusercontent.com/spring-petclinic/spring-petclinic-rest/refs/heads/master/src/main/resources/db/mysql/schema.sql -O /tmp/schema.sql
    sed -i '1 i\USE petclinic;' /tmp/schema.sql  # Add 'USE petclinic;' to the top of schema.sql
  args:
    executable: /bin/bash

- name: Populate database schema
  ansible.builtin.shell: |
    mysql -f < /tmp/schema.sql
  args:
    executable: /bin/bash

- name: Download and prepare data.sql
  ansible.builtin.shell: |
    wget -q https://raw.githubusercontent.com/spring-petclinic/spring-petclinic-rest/refs/heads/master/src/main/resources/db/mysql/data.sql -O /tmp/data.sql
    sed -i '1 i\USE petclinic;' /tmp/data.sql  # Add 'USE petclinic;' to the top of data.sql
  args:
    executable: /bin/bash

- name: Populate database data
  ansible.builtin.shell: |
    mysql -f < /tmp/data.sql
  args:
    executable: /bin/bash
