all:
  hosts:
    frontend:
      ansible_host: 10.0.3.20
      ansible_user: Admin123
      ansible_ssh_private_key_file:  ~/wus-24z-laboratorium/lab2/terraform/private_key.pem
    backend:
      ansible_host: 10.0.2.20
      ansible_user: Admin123
      ansible_ssh_private_key_file:  ~/wus-24z-laboratorium/lab2/terraform/private_key.pem
    db_master:
      ansible_host: 10.0.1.20
      ansible_user: Admin123
      ansible_ssh_private_key_file:  ~/wus-24z-laboratorium/lab2/terraform/private_key.pem

  children:
    frontend_group:
      hosts:
        frontend

    backend_group:
      hosts:
        backend

    db_group:
      hosts:
        db_master
