- name: Deploy Database
  hosts: db_master_group
  become: true
  roles:
    - db_master

- name: Deploy DB Slave
  hosts: db_slave_group
  become: true
  roles:
    - db_slave

- name: Deploy Backend
  hosts: backend_group
  become: true
  roles:
    - backend

- name: Deploy Frontend
  hosts: frontend_group
  become: true
  roles:
    - frontend
