- name: Deploy Database
  hosts: db_group
  become: true
  roles:
    - db_master

- name: Deploy Backend
  hosts: backend_group
  become: true
  roles:
    - backend

- name: Deploy Frontend
  hosts: frontend_group
  become: true
  roles:
    - frontend
