frontend_backend_ip: "<backend_ip>"
frontend_backend_port: 
frontend_port: 8000

backend_port: 8010
backend_db_ip: "<db_ip>"
backend_db_port: 3306
backend_folder_path: "/root/petclinic_backend"

db_master_port: 3306