- name: Update and upgrade system packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist

- name: Install MySQL server
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Configure MySQL
  block:
    - name: Update MySQL configuration
      ansible.builtin.lineinfile:
        path: /etc/mysql/my.cnf
        line: "{{ item }}"
        create: yes
      with_items:
        - "[mysqld]"
        - "port={{ db_master_port }}"
        - "bind-address = 0.0.0.0"
        - "server-id = 1"
        - "log_bin = /var/log/mysql/mysql-bin.log"

    - name: Restart MySQL service
      ansible.builtin.service:
        name: mysql
        state: restarted

- name: Set up MySQL database and user
  ansible.builtin.shell: |
    mysql -e "CREATE USER IF NOT EXISTS 'petclinic'@'%' IDENTIFIED BY 'petclinic';"
    mysql -e "CREATE DATABASE IF NOT EXISTS petclinic;"
    mysql -e "GRANT ALL PRIVILEGES ON petclinic.* TO 'petclinic'@'%' WITH GRANT OPTION;"
    mysql -e "CREATE USER 'replica_petclinic'@'%' IDENTIFIED WITH mysql_native_password BY 'replica_petclinic';"
    mysql -e "GRANT REPLICATION SLAVE ON *.* TO 'replica_petclinic'@'%';"
    mysql -e "FLUSH PRIVILEGES;"
  args:
    executable: /bin/bash
