- name: Update and upgrade system packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist

- name: Install Node.js and npm
  apt:
    name:
      - nodejs
      - npm
    state: present
    update_cache: yes

- name: Install NVM
  ansible.builtin.shell: |
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  args:
    executable: /bin/bash

- name: Load NVM environment
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    nvm install 16
  args:
    executable: /bin/bash

- name: Clone frontend repository
  ansible.builtin.git:
    repo: https://github.com/spring-petclinic/spring-petclinic-angular
    dest: /root/spring-petclinic-angular

- name: Update environment files
  ansible.builtin.replace:
    path: "/root/spring-petclinic-angular/{{ item }}"
    regexp: "localhost"
    replace: "{{ frontend_backend_ip }}"
  with_items:
    - src/environments/environment.prod.ts
    - src/environments/environment.ts

- name: Replace backend port
  ansible.builtin.replace:
    path: "/root/spring-petclinic-angular/{{ item }}"
    regexp: "9966"
    replace: "{{ frontend_backend_port }}"
  with_items:
    - src/environments/environment.prod.ts
    - src/environments/environment.ts

- name: Install frontend dependencies and build
  shell: |
    cd /root/spring-petclinic-angular
    npm install
    npm install -g angular-http-server
    npm run build -- --configuration production
  args:
    executable: /bin/bash

- name: Start Angular server
  ansible.builtin.shell: |
    cd /root/spring-petclinic-angular/dist
    nohup npx angular-http-server --path ./ -p {{ frontend_port }} > angular.out 2> angular.err &
  args:
    executable: /bin/bash
